#random_number=$((2 + RANDOM % 2))
# always display text instead random chance
random_number=1

if [ $random_number -eq 1 ]; then
	quotes=(
		"Kóreai Péniszhal"
		"🗿"
		"Lombkoronamentes-sétány"
		"Félkengyelmű"
		"Glory to Arstotzka!"
		"Kalapács Malter"
		"Toronymentesítést vállalunk!"
		"Dedikált légitár"
		"Derékszög Tagadók Tagadók (Tagadók) Klubja"
		"Citromos Almaleves"
		"Kecsöpös instantgofri - fahéjjal"
		"Bread Sheeran"
		"Kakaós Spirál"
		"Bojler eladó"
		"Turi ip ip ip"
		"I used to tickle my pickle to Angry Birds"
		"Brüsszeli Szankciós Poroltó"
		"Nvidia elemehet kukutyinba zabot hegyezni"
		"Yapping level today: Catastrophic"
		"womp womp"
		"Crazy? I was crazy once..."
		"Chipi Chipi Chapa Chapa Dubi Dubi Daba Daba"
		"Anális Gyorsítás"
		"Kicsit elszomorít hogy nem vagy proud rám... ennél többet vártam tőled"
		"ImpulzusSzélességModulációAlapúElektroMotorVezérlésAFelhasználásHelyénProgramozhatóLogikaiKapumátrixxal"
		"A halak megölték a macskákat!!!"
		"A madarak megölték a macskákat!!!"
		"Lilahajú Kalóriaharcosok"
		"Rovátkolt Barom"
		"I may just have rm -rf-ed my homework"
		"Na mondom mi a szitu; te lány én meg fiú"
		"Bro is the Rizard of Oz"
		"Öt éjszaka Frédérik Fázermackó Ferdinánd Pizzériájában"
		"Kenyeret kenyért"
		"Kronométer"
		"Szalmapityóka"

		"A YT Music elfelejtette a hangot lejátszani a zeném mellé"
		"Epével kevert bort adtak neki"
		"Vedd ki előbb saját szemedből a gerendát"
		"Csak a biosztanár meg a britek mondják úgy hogy hímvessző"
		"Elemzés Poloska Peti karórájáról"
		"Antipedofidesz"
		"heteropaternális szuperfekundáció"
		"Foghijas alkoholista drogos szennycsatorna parazita rágcsálok"
		"A bogárból van kettő darab is"
		"Úgy görbíti a valóságot, mint feketelyuk a téridőt."
		"Ha a New Yorkiak New Yorkerek, a Hamburgiak Hamburgerek?"
		"Van egy rosszhírem ukik..."
		"A terhes feleségét ajtónak vágó Magyar Péter - Origó"
		"Ha valaki rákérdez valamire, hogy nem mindegy? Nem! Na mindegy"
		"Szíveskedjék kikapcsolt állapotba helyezni az internet-készülékét."
		"Matyi úgy böfög mint egy gejzír. (extradús Szentkirályi referencia)"
		"A bodag avagy cigánykenyér egyszerűen és viszonylag gyorsan elkészíthető kenyérféleség."
		"Most vissza kell szinteznem az oceánt mert valaki elvitte" #levellelnem 
#		"In the 12 days of Rizzmas, my Rizzler gave to me..."
		"Mióta eltörtem a plazmagömböt, azóta nyikorog a kisujjam"
#		"Nyem táncolyunk úty, ahoty Prüsszel fügyül"
		"Ember, most jövök a Netherből"
		"Magyarország előre megy, csak rossz irányba"
		"Csak úgy kérdezem, a vért mivel lehet lemosni a csempéről?"
		"Ettől hihetetlenül kedvem támadt konnektorba villát dugni"
		"Te jönnél felgyújtani egy kanapét és közbe rapet forgatni rajta?"
		"Van egy szál buszjegyed? Kéne cigire"
		"Átlagos Kőbányai pincerendszer élvezők klubja"
		"Ami úgy néz ki, mint egy gitár, az egy gitár."
		"Ukrajna elfogyott, Románia nem is volt"
		"Ja, én is minden reggel félúton nemet váltok a buszon"
		"Te menj előre, mert neked nincs skined (CS:GO rizz)"
		"Magyar ember nem teszi zsebre a palacsintát"
		"Nem úszod meg sem vízesen, sem szárazon"
		"Inkább megfulladnál egy darab narancstól vagy félrenyelnéd a saját nyelésed?"
		"Ha nem tudnám hogy nem én vagyok, azt hinném, hogy én vagyok"
		"Nem mindegy, hogy szarba csapni, vagy csapba szarni"
		"There's a difference between shitting in the sink and sinking in the shit."
		"Inkább megnyúznának roston sütve, vagy elszívnál egy almát?"
		"Nem minden vese, ami vérzik"
		"Mióta finom a finomfőzelék??"
		"Ne kezelje a halat gyanút keltő körülmények között."
		"Rejtélyes körülmények közt hatszor kiesett a nyolcadikról miután hátbalőtte magát dekopírfűrésszel."
		"Jönnek a fenyegető aurájú grafikonok!!"
		"Kidodgeoltam a Skeleton lövését, most Neonak érzem magam a mátrixból"
		"Én sütöm az összes krumplit szóval mérges kell hogy legyek"
		"Amikor eldurran és az egész konyha olyan lesz"
		"Te is jössz vasárnap Nagykátára tököt lopni?"
		"Ebből tehervonat lesz"
		"Ha elrontottad az azért van mert még nem tanultuk"

		"A bocskor az egy cipő"
		"Elnézést, maga bolond?"
		"Mit építesz? - Üvegherét"
		"Te egész nap csak így vagy? Nem csoda hogy ilyen vasfarmunk van"
		"Mit gondoltál, jó ötlet hogy álljunk neki kalapáccsal? Nem, asztallábbal!"
		"2 kanál mosószóda BioTech USA dobozban? Ezt ki mondta??"
		"Nem a legfiókabb él a késben"
		"Valóságtartalommal rendelkezik"
		"Nyöpni kelni nem tudott"
		"Kakaós billentyű damping"
		"Hangyakalács-taktika"
		"18 tonna kémény"
		"Extrudált Kenyér"
		"Ez a nő egy hárpia"
		"Mit tett veled a tej"
		"Ja hogy be kell kapcsolni! Vagyúgy!"
		"Valóban?"
		"Görög van a falóban"
		"mondta a kobra és eldőlt jobbra"
		"pszichopata droid"
		"Egy kis palacsintát a nutelládhoz?"
		"Inkább gyaloglok síneken mint ülök németen"
		"Meki gegangen"
		"Paprikáskakas"
		"Megyek és repülök; Ne repülj gyere; Akkor gyalog repülök"
		"Egy őrült élő halottlátó hulla"
		"És ha él akkor nem halt meg. De akkor hova lett?"
		"Odaült a fal?"
		"Megáll az ész! Ön tényleg építész??"
		"Sérti a külleme a szépérzékemet"
		"Mi ez falusi kolbász? Nem dehogy, városi szalámi"
		"Tessék felírni: röff röff = oink oink"
		"Doktor Szent kenyérpirító Botond"
		"Most hogy betoltál egy vödör virágot..."
		"reflexből megetted"
		"A virágokat vidd már haza - miért - megyek inni"
		"Egy baj van a képekkel, hogy kicsit olyan cigányos"
		"Újsütetű öregdiák"
		"Kajla kiskamasz"
		"tehenes májvakarókrémes lövés"
		"Matyinak be fog csúszni a barna maci you feel me"
		"Azonnali engedélyt kérünk a véccé használatára"
		"Innen is látszik hogy maga is a Gyurcsány show része"
		"Felcsúti pénznyerő varangy"
		"Miért kell neked Fortnite raphez dalszöveg??"
		"amúgy mostanában egyre erősebb vonzalmat kezdek érezni a háromfázisú indukciós főzőlapvezérlők iránt"
		"Szőke Mátyás fényboltja"
		"mi a neved? Szőke Mátyás és az y egy yen jellel van írva"
		"Bebootol a géped és nem indul el semmi csak a nyers Fortnite"
		"Így hibásan léptem és a térdem bekrapált"
		"Karácsony Péter"
		"Keresett a Feri - Milyen kádat?"
		"még csak ideiglenesen merült le"
		"Ma szombaton valaki tegnap lehoppolt"
		"miért nem a 2. világháború volt előbb? sokkal fireebb volt"
		"I wish there was a reptér - Liszt:"
		"Nem távoli, tehát közeli"
		"Bistabil Multivibrátor"
		"Astabil Multivibrátor"
		"És a rezsó hol a faszomban van"
		"...a harmadik pedig a buttplugos basszus"
		"imád lamentálni az erotikus részein a biblián"
		"A van és jó az nekem nem opció"
		"Ott állottam immár a hit mérővesszelyén"
		"Mélylélektani írásmód"
		"Futóbolond"
		"A szomszéd nője mindig szűkebb"
		"Miért tértünk át hip-hop perfektre?"
		"Megyek malacot takarítani csak előtte levakolom a waxot a pecsétről"
		"biciklikus"
		"A borsó méretűre felduzzadt puding a fejedben"
		"Fogon ütöttem magam"
		"valakinek csak a jégkása operál a fejében"
		"Hungaroid Idiotizmus"
		"Ribancpálca"
		"Borsót Gömbölyít"
		"Zabot hegyez"
		"Felső Majláth"
		"Olajkutató"
		"Katonazárda sarok"
		"Tornanádaska"
		"Horogkeresztúri"
		"átváltottam brainrot módba"
		"Circus Maximus túra"
		"Pénz számolva, asszony verve"
		"cselszövő csibész cigány"
		"A nyelvnyújtogatós kurva anyját"
		"homogoblin"
		"az a guruló gömbalakú ogre elkezd nekem itt papolni"
		"Legyen olyan évszak ahol jézusom megerőszakol az enderman"
		"8? akkor parfümöt is kell feltenni"
		"Nem nehéz mert OpenGL"
		"Ami nincs az nem tud rohadni"
		"Még a betonból is kinő a fa"
		"Eddig tök nyugodtam csóróskodtam"
		"Csak hajtogatok és lélegzem"
		"Ebből a levest talán hallottam is"
		"Miért van télapó Szobon??"
		"Megérkeztünk Zebegényre"
		"Magasság lemérve, vélemény ignorálva"
		"Cipel egy rekesz vizet, mert hát mit csinálna"
		"Ott él már az ablakban egy 7 generációs pókcsalád"
		"Bro elszámolta a viccet"
		"to π or not to π"
		"Kamrahaszna"
		"nuddle"
		"A házi feladat lesz ezt megérteni"
		"Szívesen likvidálnálak ingyen és bérmentve"
		"Fügyülük a salátára"
		"Papida megette midnight snacknek"
		"Édes lepénykülönlegességek"
		"Egy köbméter házit ad"
		"Van baj itt szatyorral"
		"Kovácsból az ács stimmelt"
		"2000 Ft-ból felrobbanthatom a Karinthyt???"
		"hegyi ukránok"
		"Zebulont szaktanári figyelmeztetésben részesítem miután lefingotta osztálytársát!"
		"Regenbogen"
		"das Design"
		"Mi történt a hajával, miért néz ki úgy mint egy seprű??"
		"kb seprű állaga van a hajának"
		"rénszarvas-szemgödörzsír"
		"kifinomult hajkezelő látható"
		"másodfokú tüdőgyulladás"
		"II. András és a nők"
		"te hülye vagy, mit esztergálsz itt, menj vissza tanulni"
		"Aranylövés"
		"valami testépítő vagy kiscserkész"	
		"Ki sírt? a fasírt"
		"The arrival of the cumans"
		"anal execution"
		"bakukan kubu"
		"Something big and frightening is coming"
		"Kötöny"
		"Csőkutya"
		"The magical poop stealing water chair"
		"agya van, csak nem tudjuk mire használja"
		"Hortobágy Berettyó"
		"Alsódomború"
		"3 szelet kőkemény kenyér"
		"Citromízű banán"
		"Csabainál beállt a lemez"
		"Hugysavkő"
		"Na ki halt meg hugyhólyagrepedésben?"
		"if: Szőkemátyás Mentioned: Put image szmatyi.png"
		"SSH: SuperShell"
		"Uborkára tűzött patkány"
		"John war sad"
		"Útba van egy erdő? Nem baj kivágom, annyira nem sürgős"
		"Szobám sarkában van egy álló merevedő ventilátor"
		"és a kisgyerekek inkább mosószert isznak ahelyett hogy zöldséget ennének"
		"Szakállas agáma"
		"Tavaly én nem én voltam"
		"Agresszív kismalac"
		"és nyújta feléd a Kovács krémet"
		"Még akkoris ha párás meg büdös, legalább hűvös"
		"Learn how to make tasty apple pies. Eat them."
	)


    # Choose a random quote from the list
    selected_quote="${quotes[RANDOM % ${#quotes[@]}]}"

    echo -e "\033[3;37m\"$selected_quote\"\033[0m"
fi

